#!/usr/bin/ansible-playbook
---
- name: manage ssl certificates
  hosts: all
  become: yes
  gather_facts: no

  vars:
    workdir: /var/certs

  vars_prompt:
    - name: fqdn
      prompt: "Common Name"
      type: String
      private: no
    - name: o
      prompt: Organization Name
      type: String
      private: no
    - name: ou
      prompt: Organizational Unit Name
      type: String
      private: no
    - name: e
      prompt: Email Address
      type: String
      private: no
    - name: c
      prompt: Country Name
      type: String
      private: no
    - name: st
      prompt: State or Province Name
      type: String
      private: no
    - name: l
      prompt: Locality
      type: String
      private: no

  roles:
    - name: setup
      setup_workdir: "{{ workdir }}"
      setup_fqdn: "{{ fqdn }}"
    - name: csr
      csr_common_name: "{{ fqdn }}"
      csr_organization_name: "{{ o }}"
      csr_organization_unit_name: "{{ ou }}"
      csr_email_address: "{{ e }}"
      csr_country_name: "{{ c }}"
      csr_state_or_province_name: "{{ st }}"
      csr_locality_name: "{{ l }}"
    - name: challenge
    - name: verify-easydns 
      verify_easydns_api_token: "{{ easydns_api_token }}"
      verify_easydns_api_key: "{{ easydns_api_key }}"
      verify_easydns_domain: "{{ easydns_domain }}"
      when: challenge is changed
    - name: challenge
      when: challenge is changed
    - name: cleanup-easydns 
      cleanup_easydns_api_token: "{{ easydns_api_token }}"
      cleanup_easydns_api_key: "{{ easydns_api_key }}"
      cleanup_easydns_domain: "{{ easydns_domain }}"
      when: challenge is changed
