- name: publish host certs to s3 bucket
  aws_s3:
    aws_access_key: "{{ publish_s3_access_key }}"
    aws_secret_key: "{{ publish_s3_secret_key }}"
    bucket: "{{ publish_s3_bucket }}"
    object: "{{ inventory_hostname }}/{{ item.obj }}"
    src: "{{ item.src }}"
    mode: put
  loop:
    - obj: "privkey.pem"
      src: "{{ privkey }}"
    - obj: "csr.pem"
      src: "{{ csr }}"
    - obj: "cert.pem"
      src: "{{ cert }}"
    - obj: "fullchain.pem"
      src: "{{ fullchain }}"
    - obj: "chain.pem"
      src: "{{ chain }}"
  loop_control:
    label: "{{ item.obj }}"
  delegate_to: "{{ delegation_target | default(localhost) }}"